trigger:
- develop

pool:
  name: APPSEALING

parameters:
- name: APPLE_ID
  type: string
  default: 'puzznic@inka.co.kr'
- name: APP_SPECIFIC_PASSWORD
  type: string
  default: 'qbrz-hmfz-robj-eohm'
- name: TEAM_ID
  type: string
  default: '22X77ENQ2H'
- name: PROVISIONING_PROFILE_NAME
  type: string
  default: 'AppSealing Wildcard Distribution Profile'

steps:
- script: |
    # Check if Flutter is installed, if not, install it
    if ! command -v flutter &> /dev/null
    then
        echo "Flutter is not installed. Installing Flutter..."

        # Install dependencies
        brew install --cask flutter

        # Verify installation
        flutter --version
    else
        echo "Flutter is already installed."
    fi
    
    # Define paths
    P12_CERT_PATH="$(Build.SourcesDirectory)/distribution.p12"
    PROVISIONING_PROFILE_PATH="$(Build.SourcesDirectory)/profile.mobileprovision"
    KEYCHAIN_PATH="$HOME/Library/Keychains/temp-keychain.keychain-db"
    KEYCHAIN_PASSWORD="temp123"

    if security list-keychains | grep -q "temp-keychain.keychain-db"; then
        echo "Deleting existing temporary keychain..."
        security delete-keychain "$KEYCHAIN_PATH"
    fi

    echo "Creating temporary keychain..."
    security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

    echo "Setting temporary keychain as default..."
    security list-keychains -d user -s "$KEYCHAIN_PATH"
    security default-keychain -s "$KEYCHAIN_PATH"
    security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    security set-keychain-settings -lut 3600 "$KEYCHAIN_PATH"

    echo "Importing distribution certificate (PKCS#12) into temporary keychain..."
    security import "$P12_CERT_PATH" -k "$KEYCHAIN_PATH" -P "123456" -T /usr/bin/codesign
    security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    security find-identity -v "$KEYCHAIN_PATH"
  displayName: 'Setup Temporary Keychain and Install Certificate'

- script: |
    # Flutter 프로젝트에서 iOS 설정 확인
    SCHEME_NAME=$(flutter doctor -v | grep -A 1 "iOS toolchain" | tail -n 1 | awk '{print $1}')
    APP_NAME="Runner"
    echo "##vso[task.setvariable variable=SCHEME_NAME]$SCHEME_NAME"
    echo "##vso[task.setvariable variable=APP_NAME]$APP_NAME"
    echo "##vso[task.logissue type=warning] Extracted SCHEME_NAME: $SCHEME_NAME"
    echo "##vso[task.logissue type=warning] Extracted APP_NAME: $APP_NAME"
  displayName: 'Extract Scheme and App Name'

- script: |
    # Increment build number in Flutter project
    cd "$(Build.SourcesDirectory)"
    flutter pub get

    # Fetch the current build number
    CURRENT_BUILD_NUMBER=$(agvtool what-version -terse)
    NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))

    # Set the new build number using agvtool
    agvtool next-version -all
    NEW_BUILD_NUMBER=$(agvtool what-version -terse)
    echo "##vso[task.setvariable variable=BUILD_NUMBER]$NEW_BUILD_NUMBER"
    echo "##vso[task.logissue type=warning] New Build Number: $NEW_BUILD_NUMBER"
  displayName: 'Increment Build Number'

- script: |
    # Extract bundle ID from Flutter's iOS configuration
    INFO_PLIST_PATH="$(Build.SourcesDirectory)/ios/Runner/Info.plist"
    BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$INFO_PLIST_PATH" 2>/dev/null)

    if [[ -z "$BUNDLE_ID" ]]; then
        echo "CFBundleIdentifier not found in Info.plist. Exiting."
        exit 1
    fi

    echo "Final BUNDLE_ID: $BUNDLE_ID"
    echo "##vso[task.setvariable variable=BUNDLE_ID]$BUNDLE_ID"
    echo "##vso[task.logissue type=warning] Extracted Bundle ID: $BUNDLE_ID"

    # Create ExportOptions.plist after extracting the Bundle ID
    EXPORT_DIR="$HOME/exports"
    mkdir -p "$EXPORT_DIR"
    cat << EOF > "$EXPORT_DIR/ExportOptions.plist"
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>method</key>
        <string>app-store</string>
        <key>teamID</key>
        <string>${{ parameters.TEAM_ID }}</string>
        <key>provisioningProfiles</key>
        <dict>
            <key>$BUNDLE_ID</key>
            <string>${{ parameters.PROVISIONING_PROFILE_NAME }}</string>
        </dict>
    </dict>
    </plist>
    EOF

    echo "ExportOptions.plist created with provisioningProfiles and bundle ID."
    cat "$EXPORT_DIR/ExportOptions.plist"  # Output the created plist content for debugging
  displayName: 'Extract Bundle ID and Create ExportOptions.plist'

- script: |
    # Define paths for Flutter iOS build
    EXPORT_DIR="$(Build.ArtifactStagingDirectory)"
    IPA_PATH="$EXPORT_DIR/$(APP_NAME).ipa"
    ARCHIVE_PATH="$EXPORT_DIR/$(APP_NAME).xcarchive"
    WORKSPACE_PATH="$(Build.SourcesDirectory)/ios/Runner.xcworkspace"

    # Ensure minimum deployment target is set
    /usr/libexec/PlistBuddy -c "Set :IPHONEOS_DEPLOYMENT_TARGET 12.0" "$(Build.SourcesDirectory)/ios/Runner/Info.plist"

    # Build iOS Flutter app
    flutter build ios --release --no-codesign

    # Create .xcarchive
    xcodebuild -workspace "$WORKSPACE_PATH" \
               -scheme 'Runner' \
               -sdk iphoneos \
               -configuration 'Release' \
               clean archive \
               CODE_SIGN_IDENTITY="iPhone Distribution" \
               CODE_SIGN_STYLE="Manual" \
               DEVELOPMENT_TEAM="${{ parameters.TEAM_ID }}" \
               PROVISIONING_PROFILE_SPECIFIER="${{ parameters.PROVISIONING_PROFILE_NAME }}" \
               -archivePath "$ARCHIVE_PATH"

    # Export IPA file
    xcodebuild -exportArchive \
      -archivePath "$ARCHIVE_PATH" \
      -exportOptionsPlist "$EXPORT_DIR/ExportOptions.plist" \
      -exportPath "$EXPORT_DIR"

    echo "IPA successfully exported: $IPA_PATH"
  displayName: 'Build and Export IPA'

- script: |
    # Grant execution permission to generate_hash script
    HASH_SCRIPT_PATH="$(Build.SourcesDirectory)/AppSealingSDK/Tools/generate_hash"
    IPA_PATH="$(Build.ArtifactStagingDirectory)/$(APP_NAME).ipa"

    echo "Granting execution permission to generate_hash..."
    chmod +x "$HASH_SCRIPT_PATH"

    echo "Running generate_hash with IPA..."
    "$HASH_SCRIPT_PATH" "$IPA_PATH"

    echo "Hash generation completed."
  displayName: 'Run generate_hash on IPA'

- script: |
    set -x
    xcrun altool --upload-app -f "$(Build.ArtifactStagingDirectory)/$(APP_NAME).ipa" -t ios -u "${{ parameters.APPLE_ID }}" -p "${{ parameters.APP_SPECIFIC_PASSWORD }}"
  displayName: 'Upload to TestFlight'

- script: |
    echo "Deleting temporary keychain..."
    TEMP_KEYCHAIN_PATH="$HOME/Library/Keychains/temp-keychain.keychain-db"
    if [ -f "$TEMP_KEYCHAIN_PATH" ]; then
        # Delete only the temporary keychain, not the default login keychain
        security delete-keychain "$TEMP_KEYCHAIN_PATH"
        echo "Temporary keychain deleted successfully."
    else
        echo "Temporary keychain not found. Skipping deletion."
    fi
  displayName: 'Cleanup Temporary Keychain'
